-- Rode este arquivo no SQL Editor do Supabase.

create table if not exists public.people (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists people_name_lower_unique
  on public.people (lower(name));

create table if not exists public.gifts (
  id bigint generated by default as identity primary key,
  person_id bigint not null references public.people(id) on delete cascade,
  title text not null,
  note text,
  link text,
  image text,
  claimed boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists gifts_person_id_idx on public.gifts(person_id);

-- Bucket público somente para leitura das imagens. O backend usa a Secret Key
-- para fazer upload/remover arquivos sem expor essa chave no navegador.
insert into storage.buckets (id, name, public)
values ('gift-images', 'gift-images', true)
on conflict (id) do update set public = true;

-- O backend faz as operações do Storage com Secret Key.
-- Não coloque a SUPABASE_SECRET_KEY no frontend.
